version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=<timezone>
      - PLEX_CLAIM=
      - PUID=0
      - PGID=0

    network_mode: host
    volumes:

      - /media:/data